dateModified: 1640119417
email:
  fromEmail: chris@malven.co
  fromName: 'Craft Vite'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    a73581f1-a52b-4e6b-a1c1-e953a1542a1e: Common # Common
    b88e951f-c11b-4abc-acd9-55c9f6c8f811: 'Craft Vite' # Craft Vite
    fd344bcc-b1ad-4cdc-9c41-e02bc08d2a41: 'Craft Vite' # Craft Vite
plugins:
  assetrev:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '1.2'
  blitz:
    edition: standard
    enabled: true
    licenseKey: PCVVBUATPAXU4AP49J28MJP3
    schemaVersion: 3.10.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-nav:
    edition: standard
    enabled: true
    schemaVersion: 2.0.7
    settings:
      originalNavHash:
        __assoc__:
          -
            - d614ac2c-aa66-4f6c-be45-70b4b9f6db79
            - W3sibGFiZWwiOiJEYXNoYm9hcmQiLCJ1cmwiOiJkYXNoYm9hcmQiLCJmb250SWNvbiI6ImdhdWdlIn0seyJsYWJlbCI6IlNFTyIsInVybCI6InNlb21hdGljIiwiaWNvbiI6Ii9Vc2Vycy9jbWFsdmVuL0NvZGUvY3JhZnQtdml0ZS92ZW5kb3IvbnlzdHVkaW8xMDcvY3JhZnQtc2VvbWF0aWMvc3JjL2ljb24tbWFzay5zdmciLCJzdWJuYXYiOnsiZGFzaGJvYXJkIjp7ImxhYmVsIjoiRGFzaGJvYXJkIiwidXJsIjoic2VvbWF0aWMvZGFzaGJvYXJkIn0sImdsb2JhbCI6eyJsYWJlbCI6Ikdsb2JhbCBTRU8iLCJ1cmwiOiJzZW9tYXRpYy9nbG9iYWwvZ2VuZXJhbCJ9LCJjb250ZW50Ijp7ImxhYmVsIjoiQ29udGVudCBTRU8iLCJ1cmwiOiJzZW9tYXRpYy9jb250ZW50In0sInNpdGUiOnsibGFiZWwiOiJTaXRlIFNldHRpbmdzIiwidXJsIjoic2VvbWF0aWMvc2l0ZS9pZGVudGl0eSJ9LCJ0cmFja2luZyI6eyJsYWJlbCI6IlRyYWNraW5nIFNjcmlwdHMiLCJ1cmwiOiJzZW9tYXRpYy90cmFja2luZy9ndGFnIn0sInBsdWdpbiI6eyJsYWJlbCI6IlBsdWdpbiBTZXR0aW5ncyIsInVybCI6InNlb21hdGljL3BsdWdpbiJ9fX0seyJ1cmwiOiJ1dGlsaXRpZXMiLCJsYWJlbCI6IlV0aWxpdGllcyIsImZvbnRJY29uIjoidG9vbCIsImJhZGdlQ291bnQiOjF9LHsidXJsIjoic2V0dGluZ3MiLCJsYWJlbCI6IlNldHRpbmdzIiwiZm9udEljb24iOiJzZXR0aW5ncyJ9LHsidXJsIjoicGx1Z2luLXN0b3JlIiwibGFiZWwiOiJQbHVnaW4gU3RvcmUiLCJmb250SWNvbiI6InBsdWdpbiJ9XQ==
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  empty-coalesce:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  environment-label:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  imager-x:
    edition: lite
    enabled: true
    licenseKey: DJSVGZCC47UCHR3EU7HSQSR7
    schemaVersion: 3.0.0
  matrixmate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: GZ7SXFM975I4WSAJA7R6CY60
    schemaVersion: 3.0.11
  snitch:
    edition: standard
    enabled: true
    schemaVersion: 2.1.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  svgplaceholder:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  twig-perversion:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  wordsmith:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0.0
system:
  edition: solo
  live: true
  name: 'Craft Vite'
  schemaVersion: 3.7.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
